[project]
name = "mc-match"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Piexgear", email = "davidpuscas@live.se" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
]

[project.scripts]
mc-match = "mc_match:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
